echo off
ssh root@178.62.201.149 "./hax.sh"
echo.
echo "                  .-'''/.\"
echo "                 (_.--'  |"
echo "                  |  ==  |"
echo "             o-._ .--..--. _.-o"
echo "                 |   ||   |"
echo "                  ;--|`--:"
echo "                  |. |   |"
echo "                  |  ;_ .|"
echo "                  |_____ |"
echo "                 /|     '|\"
echo "                 //`----'\\"
echo "                ////|  |  \\"
echo "                /   |  |    \"
echo "                   /|  |\"
echo "                  / \  / \"
echo "                 /   \/   \"
echo "                /          \"
echo "                |          |"
echo "               ||    /\    ||"
echo "               ||   ,  .   ||"
echo.
echo "          -- fixed that for you"
